name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: orders
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, dom, fileinfo, mysql
          coverage: none

      - name: Copy .env
        run: cp -v ci.env .env

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v3
        with:
          path: |
            vendor
            !vendor/**/tests
            !vendor/**/docs
            !vendor/**/examples
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Optimize Project
        run: php artisan optimize:clear

      - name: Run migration
        run: php artisan migrate:fresh --seed

      - name: Run tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: orders
          DB_USERNAME: root
          DB_PASSWORD: password
          REDIS_HOST: 127.0.0.1
          REDIS_PASSWORD: ""
          REDIS_PORT: 6379
        run: php artisan test
